### ISSUE TITLE
Question about organizing the content!

### ISSUE THREAD

**Issue by sarsanaee** [lastweek/FPGA#1]
Hi,

This is a really cool repository for two main reasons! First is that I like the incentives regarding learning FPGAs, second, the manner that you have about how you are getting started with this research area.

I was looking at different places to learn more about this area since we can see so many specialized devices for data center applications like programmable NICs, Switches, accelerators for Graph Processing and ... I also really like the paper at OSDI'18 - "Sharing, Protection, and Compatibility for Reconfigurable Fabric with AmorphOS." They have not shared so many details about the implementation stuff unlike your paper there!

Anyway, I would be happy to contribute to this repository. You shared a lot in this repository, however, that would be awesome if you could add a section in the README.md indicating the best order of reading the content there! 

The `Get Started` section is also pretty packed, it is possible to look through all content but it is not time efficient.  The `RapidWright FPGA Architecture Basics` was really good for me! Like there are a couple of courses and you marked one of them as the most practical one, and that would be the one I read first!

**Comment by lastweek** [comment]
Hi @sarsanaee 

Thank you for your interest in this repo! I think you are right, the README and xilinx.md are now super packed. In my this week's spare time, I will reorder some of the text, and add a section in the README about the learning orderings.

And I will be more than happy if you could contribute. After all, this repo is intended for people like us who just started learning FPGA, and for us to share our experiences.
